server:
  port: 8080
  servlet:
    context-path: /masada/marketstack

api:
  url: ${MARKETSTACK_API_URL:https://api.marketstack.com/v1}
  key: ${MARKETSTACK_API_KEY:12f3000470ebddaf371dc910c48cbe85}

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/masada}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASS:root}